CREATE TABLE Customers
(
id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(100),
CIN FLOAT DEFAULT 0,
COUT FLOAT DEFAULT 0
)
GO
CREATE TABLE Items
(
id INT PRIMARY KEY IDENTITY(1,1),
ItemName NVARCHAR(100),
Price FLOAT DEFAULT 0,
Amount FLOAT DEFAULT 0
)
CREATE TABLE InvoiceType
(
id TINYINT PRIMARY KEY,
Typ NVARCHAR(50)
)
GO
CREATE TABLE Invoice
(
INVID INT PRIMARY KEY,
FK_CustomerID INT FOREIGN KEY REFERENCES Customers(id),
FK_TypeID TINYINT FOREIGN KEY REFERENCES InvoiceType(id),
INDate DATE,
Total FLOAT,
Paid FLOAT,
Remaind FLOAT,
IsDeleted BIT DEFAULT 0 
)
GO
CREATE TABLE InvoiceDetails
(
id BIGINT PRIMARY KEY IDENTITY(1,1),
FK_InvoiceID INT FOREIGN KEY REFERENCES Invoice(INVID),
FK_ItemID INT FOREIGN KEY REFERENCES Items(id),
Price FLOAT,
QTY FLOAT,
Total FLOAT
)
GO
CREATE TABLE RefundInvoice
(
RINVID INT PRIMARY KEY,
FK_CustomerID INT FOREIGN KEY REFERENCES Customers(id),
FK_InvoiceID INT FOREIGN KEY REFERENCES Invoice(INVID),
FK_TypeID TINYINT FOREIGN KEY REFERENCES InvoiceType(id),
RINDate DATE,
Total FLOAT,
IsDeleted BIT DEFAULT 0
)
GO
CREATE TABLE RefundINVDetails
(
id BIGINT PRIMARY KEY IDENTITY(1,1),
FK_RInvoiceID INT FOREIGN KEY REFERENCES RefundInvoice(RINVID),
FK_ItemID INT FOREIGN KEY REFERENCES Items(id),
Price FLOAT,
QTY FLOAT,
Total FLOAT
)
GO
CREATE TABLE CashReciept
(
CRID INT PRIMARY KEY IDENTITY(1,1),
FK_CustomerID INT FOREIGN KEY REFERENCES Customers(id),
FK_InvoiceID INT FOREIGN KEY REFERENCES Invoice(INVID),
CRDate DATE,
Total FLOAT
)
GO