//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReciept
    {
        public int CRID { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public Nullable<int> FK_InvoiceID { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
