//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.CashReciept = new HashSet<CashReciept>();
            this.InvoiceDetails = new HashSet<InvoiceDetails>();
            this.RefundInvoice = new HashSet<RefundInvoice>();
        }
    
        public int? INVID { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public Nullable<int> FK_TypeID { get; set; }
        public Nullable<System.DateTime> INDate { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Remaind { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashReciept> CashReciept { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual InvoiceType InvoiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundInvoice> RefundInvoice { get; set; }
    }
}
