//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetails
    {
        public long id { get; set; }
        public Nullable<int> FK_InvoiceID { get; set; }
        public Nullable<int> FK_ItemID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Items Items { get; set; }
    }
}
