//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefundInvoice()
        {
            this.RefundINVDetails = new HashSet<RefundINVDetails>();
        }
    
        public int? RINVID { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public Nullable<int> FK_InvoiceID { get; set; }
        public Nullable<int> FK_TypeID { get; set; }
        public Nullable<System.DateTime> RINDate { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual InvoiceType InvoiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundINVDetails> RefundINVDetails { get; set; }
    }
}
